#!/bin/bash

export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

command -v pn || alias pn='pnpm'

# tabtab source for packages
# uninstall by removing these lines
[ -f ~/.config/tabtab/zsh/__tabtab.zsh ] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

function dotfiles-install-pnpm() {
  corepack enable
  corepack prepare pnpm@latest --activate
}
