#!/bin/bash

export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# Fix pnpm being created in "~/.local/share/pnpm"
# As we are installing with corepack,
# we can load pnpm straight from the nvm directory for the current node version
node_path=$(which node)
nvm_dir=${node_path%/node}
if [ -f "$HOME/.local/share/pnpm/pnpm" ] && [ -f "$nvm_dir/pnpm" ]; then
  ln -sf "$nvm_dir/pnpm" "$HOME/.local/share/pnpm/pnpm"
fi

command -v pn || alias pn='pnpm'
command -v pncx || alias pncx='pnpm changeset'

# tabtab source for packages
# uninstall by removing these lines
[ -f ~/.config/tabtab/zsh/__tabtab.zsh ] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

function dotfiles-install-pnpm() {
  corepack enable
  corepack prepare pnpm@latest --activate
}
