#!/bin/bash

# Git
alias glo='git log --oneline'
#alias gcom='git checkout master'

alias llog='clear; tail -f -n 0 storage/logs/laravel-$(date +%F).log'
alias prettyjson='python -m json.tool'

alias dc='docker-compose'

# Get external IP address
alias ipaddr='curl ipecho.net/plain; echo'

gcom() {
  if [[ -n $(git branch --list main) ]]; then
    git checkout main
  else
    git checkout master
  fi
}

rector() {
  docker run --rm -v "$(pwd):/project" rector/rector:latest process "/project/$1" --config="/project/rector.yaml" --autoload-file /project/vendor/autoload.php
}

docker-backup() {
  BASE_DIR="/d/backups"
  TIMESTAMP=$(date +%F)
  DATABASES=("getracker_database_1" "ezines_database_1" "cerebro_database_1")

  for DATABASE in "${DATABASES[@]}"; do
    BACKUP_DIR="${BASE_DIR}/docker/${TIMESTAMP}/${DATABASE}"
    mkdir -p "${BACKUP_DIR}"
    #		cd "${BACKUP_DIR}"
    #docker run --rm --volumes-from "${DATABASE}" -v $(pwd):/backup ubuntu:18.04 tar -czvf /backup/backup.tar.gz /bitnami/mysql/data
    docker run --rm --volumes-from "${DATABASE}" -v "${BACKUP_DIR}:/backup" ubuntu:18.04 tar -czvf /backup/backup.tar.gz /bitnami/mysql/data
    #		echo "Exit code: $CODE"
  done
}

reqtime() {
  FORMAT=" \
    time_namelookup:  %{time_namelookup}\n \
       time_connect:  %{time_connect}\n \
    time_appconnect:  %{time_appconnect}\n \
   time_pretransfer:  %{time_pretransfer}\n \
      time_redirect:  %{time_redirect}\n \
 time_starttransfer:  %{time_starttransfer}\n \
                    ----------\n \
         time_total:  %{time_total}\n"

  curl -sk -o /dev/null -w "$FORMAT" "$1"
}

speedtest() {
  curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
}

speedtest-linode() {
  # https://gist.github.com/raulmoyareyes/34cbd643e2c93be64746
  # curl -o /dev/null http://speedtest.london.linode.com/1GB-london.bin

  if [[ "$1" == "--help" ]]; then
    cat << EOF
usage: $0 [SIZE]
    --help               Show this message
    SIZE                 Speedtest download size [100MB/1GB]
EOF
    return 0
  fi

  SPEEDTEST_SIZE="$1"

  if [[ -z "$1" ]]; then
    SPEEDTEST_SIZE="100MB"
  fi

  echo "Starting $SPEEDTEST_SIZE download. Available: 100MB / 1GB"

  curl -o /dev/null "http://speedtest.london.linode.com/$SPEEDTEST_SIZE-london.bin"
}

fileinfo() {
  local FILESIZE
  local HASH
  FILESIZE=$(stat --printf="%s" "$1")
  HASH=$(sha256sum "$1" | awk -F' ' '{print $1}')
  echo "$1"
  echo "Filesize: ${FILESIZE}"
  echo -e "SHA256: ${HASH}\n"
}

ngrok-docker() {
  CMD="docker run --rm -it --name ngrok -p 4040:4040 --link $1 --network $3 -v /c/Users/James/.ngrok2/:/home/ngrok/.ngrok2/ wernight/ngrok ngrok http -subdomain=$4 $1:$2"
  echo "$CMD"
  tmux new-window "$CMD"
  tmux rename-window ngrok
}

# AWS
ec2-status() {
  aws ec2 describe-instances --instance-ids "$1" | jq ".Reservations[0].Instances[0].State.Name"
}

# Start and source a Python VirtualEnv
# venv - loads 2.7 by default
# venv 3 - loads Python 3
# venv 2/2.7 - loads Python 2.7
venv() {
  PYVER=2.7

  # Set version
  if [[ -n "$1" ]]; then
    PYVER="$1"
  fi

  if [[ "$PYVER" == "2" ]]; then
    PYVER="2.7"
  fi

  virtualenv -p "/usr/bin/python$PYVER" venv
  source venv/bin/activate
}

# Attach tmux to current working directory
tmux-cwd() {
  tmux command-prompt -I "$PWD" -p "New session dir:" "attach -c %1"
}
