#!/bin/bash

# File editor
export VISUAL=vim
export EDITOR="$VISUAL"

# pipx
export PATH="$HOME/.local/bin:$HOME/.local:$PATH"

# Linuxbrew
if [[ $(uname) == "Linux" ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [[ $(uname) == "Darwin" ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# Composer
export PATH="$HOME/.composer/vendor/bin:$PATH"

# Node / Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Custom Software
export PATH="/opt:$PATH"
