#!/bin/bash

aws-ssh() {
  ssh -i /d/Google\ Drive/Infrastructure/AWS/getracker-aws "ec2-user@$1"
}

#aws-scp() {
#	KEY="/d/Google Drive/Infrastructure/AWS/getracker-aws"
#	echo $KEY
#	echo $1
#	rsync -Pav -e 'ssh -i "$KEY"' ./public/assets/images/icons/ ec2-user@172.31.15.36:/var/www/ge-tracker.com/public/assets/images/icons/
#}

ngrok-getracker() {
  ngrok-docker getracker_appserver_1 80 getracker_default getracker
}

gt-cloc() {
  cloc --not-match-f='bootstrap' app/ packages/jamesausten/ tests/ resources/views/ public/assets/sass/ public/assets/js/getracker/ public/assets/js/graph-data-v3.js public/assets/js/angular
}

alias getracker-flush='lando composer du -o; lando artisan dev:flush-ide-helper; composer fixc'
alias gtinit='cd /d/wamp/www/getracker.local/ && tmux'
#alias ssh-aws='ssh -i /d/Google\ Drive/Infrastructure/AWS/getracker-aws ec2-user@'
#alias aws-scp='scp -i /d/Google\ Drive/Infrastructure/AWS/getracker-aws'
alias aws-scp="rsync -Pav -e 'ssh -i ~/.ssh/getracker-aws'"

