#!/bin/bash

discord-export() {
  echo "Exporting channel as HTML"
  docker run --rm -v "$(pwd):/app/out" tyrrrz/discordchatexporter export -t "$DISCORD_BOT_TOKEN" -b -c "$1" -f HtmlDark
  echo "Exporting channel as JSON"
  docker run --rm -v "$(pwd):/app/out" tyrrrz/discordchatexporter export -t "$DISCORD_BOT_TOKEN" -b -c "$1" -f Json
}

#alias dc='docker-compose'
#alias dce='docker-compose exec'

# Docker aliases
alias yaw='docker-compose exec node yarn dev'
alias yab='docker-compose exec node yarn build'
alias yat='docker-compose exec node yarn test'
alias tinker='docker-compose exec app php artisan tinker'
alias vapor='php ./vendor/bin/vapor'

alias sitespeed='docker run --rm -v "/mnt/d/Google Drive/Infrastructure:/sitespeed.io" sitespeedio/sitespeed.io:12.0.1 -b chrome'
alias coach='docker run --rm -v "/mnt/d/Google Drive/Infrastructure:/sitespeed.io" sitespeedio/coach:4.5.0 --details --description -b chrome'

alias ctop='docker run --rm -ti --name=ctop --volume /var/run/docker.sock:/var/run/docker.sock:ro quay.io/vektorlab/ctop:latest'

alias dive='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest'

# Composer local dev
composer-link() {
  jq '.repositories |= [{"type": "path", "url": "'$1'", "options": {"symlink": true}}] + . ' composer.json >composer.tmp.json && mv composer.tmp.json composer.json

  packageName=$(jq -r '.name' "$1/composer.json")

  composer require "$packageName" @dev
}

composer-unlink() {
  git checkout composer.json composer.lock
  composer update
}

# Access Redis running inside docker-compose
# Usage: redis-cli [filter]
redis-cli() {
  [ -z "$1" ] && docker-compose exec redis redis-cli
  [ -n "$1" ] && docker-compose exec redis redis-cli monitor | tee | grep "$1"
}

# PHP Compatibility checker
# composer global require phpcompatibility/php-compatibility dealerdirect/phpcodesniffer-composer-installer "squizlabs/php_codesniffer=*"
phpcc() {
  # If no directory is specified, we should automatically build directories
  if [[ -z $1 ]]; then
    AVAIL_DIRS=('app' 'src' 'tests' 'packages')
    CHECK_DIRS=''
    CHECK_DIR_CMD=''

    # Build command string if the directory exists
    for x in "${AVAIL_DIRS[@]}"
    do
      if [[ -d "$x" ]]; then
        CHECK_DIRS="$x $CHECK_DIRS"
        CHECK_DIR_CMD="-p $x $CHECK_DIR_CMD"
      fi
    done
  else
    CHECK_DIRS="$1"
    CHECK_DIR_CMD="-p $1"
  fi

  if [[ -z "$CHECK_DIR_CMD" ]]; then
    echo "No directories found in CWD from list: $AVAIL_DIRS"
    return 1
  fi

  TEST_VERSION='8.0-'
  if [[ -n $2 ]]; then
    TEST_VERSION="$2"
  fi

  RUN_CMD="phpcs $CHECK_DIR_CMD --standard=PHPCompatibility --runtime-set testVersion $TEST_VERSION"

  echo "Testing PHP compatibility for $TEST_VERSION in $CHECK_DIRS"
  eval "$RUN_CMD"
}

senv() {
  sudo -v

  BRANCH="$1"
  DUMP_PATH="/mnt/d/Google Drive/Development/2022 Rebuild/Dumps/"
  FILE_PATH=$(ls -tr "$DUMP_PATH" | grep -E "$BRANCH-.+.tar.zst" | tail -1)
  TAR_ARCHIVE=$(basename "$FILE_PATH")

  git checkout "$BRANCH"

  echo
  echo -n "Copying vendor and node_modules archive from $TAR_ARCHIVE... "
  cp "/mnt/d/Google Drive/Development/2022 Rebuild/Dumps/$TAR_ARCHIVE" .
  echo -e "${COLOR_GREEN}Done${COLOR_RESET}"

  echo -n 'Removing old vendor and node_modules... '
  sudo rm -rf vendor/ node_modules/
  echo -e "${COLOR_GREEN}Done${COLOR_RESET}"

  echo -n 'Extracting archive... '
  ztar -x "$TAR_ARCHIVE"
  rm -f "$TAR_ARCHIVE"
  echo -e "${COLOR_GREEN}Done${COLOR_RESET}"

  # Ensure husky permissions are correct
  [ -f .husky/pre-commit ] && chmod +x .husky/pre-commit
  [ -f .husky/_/husky.sh ] && chmod +x .husky/_/husky.sh
}

benv() {
  BRANCH=$(git symbolic-ref --short -q HEAD 2>/dev/null)

  if [[ "$BRANCH" == "" || "$?" -ne 0 ]]; then
    echo 'Not in a git repository'
    return 1
  fi

  DUMP_PATH="/mnt/d/Google Drive/Development/2022 Rebuild/Dumps/"
  TODAY=$(date +%Y%m%d)
  TAR_ARCHIVE="$BRANCH-$TODAY.tar.zst"

  if [[ -f "$DUMP_PATH$TAR_ARCHIVE" ]]; then
    rm -f "$DUMP_PATH$TAR_ARCHIVE"
  fi

  echo -n 'Backing up vendor and node_modules... '
  ztar "$TAR_ARCHIVE" node_modules/ vendor/
  echo -e "${COLOR_GREEN}Done${COLOR_RESET}"

  echo -n 'Moving file... '
  mv "$TAR_ARCHIVE" "$DUMP_PATH"
  echo -e "${COLOR_GREEN}Done${COLOR_RESET}"

  echo -e "${COLOR_GREEN}Created ${TAR_ARCHIVE}${COLOR_RESET}"
}

wsl-backup() {
  if [[ -z "$1" ]]; then
    echo "Usage: wsl-backup <destination>"
    return 1
  fi

  DEST="$1"
  FILE_PATH="$DEST/wsl-backup-$(date +%Y%m%d).tar.gz"

  tar -cvzf "$FILE_PATH" "$HOME"
}

# Run PHP inside a local docker container using the "getracker/php-base" image
lphp() {
  # grep -oP '"php": "(?:\^(?:\d\.\d)\|)?\^(?:\d\.\d)"' composer.json
  # if [ -f composer.json ] && grep -q '"php":' package.json ; then
  PHP_VERS="8.3"

  # if first argument patches a PHP version, use that
  if [[ "$1" =~ ^[0-9]+\.[0-9]+$ ]]; then
    PHP_VERS="$1"
    shift
  fi

  CMD_ARGS="${@}"

  # Default args to bash if not defined
  [ -z "$CMD_ARGS" ] && CMD_ARGS="bash"

  docker run --rm -it -v "$(pwd):/var/www" "getracker/php-base:${PHP_VERS}-dev_fpm" "${CMD_ARGS}"
}

nvidia-flatpak-update() {
  VERSION_FILE=/proc/driver/nvidia/version

  if [ ! -f "${VERSION_FILE}" ]; then
    echo "Nvidia driver not found (${VERSION_FILE})"
    return 1
  fi

  DRIVER_VERSION=$(awk '{print $8}' "${VERSION_FILE}" | head -1)
  FLATPAK_VERSION="${DRIVER_VERSION//./-}"

  echo -e "Installing flatpak drivers for version ${COLOR_GREEN}${DRIVER_VERSION}${COLOR_RESET}\n"

  flatpak install --user flathub "org.freedesktop.Platform.GL.nvidia-${FLATPAK_VERSION}/x86_64" "org.freedesktop.Platform.GL32.nvidia-${FLATPAK_VERSION}/x86_64"
}

cl-help() {
  echo -e "${COLOR_GREEN}build${COLOR_RESET}\t\t Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
  echo -e "${COLOR_GREEN}chore${COLOR_RESET}\t\t Other changes that don't modify src or test files"
  echo -e "${COLOR_GREEN}ci${COLOR_RESET}\t\t Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
  echo -e "${COLOR_GREEN}docs${COLOR_RESET}\t\t Documentation only changes"
  echo -e "${COLOR_GREEN}feat${COLOR_RESET}\t\t A new feature"
  echo -e "${COLOR_GREEN}fix${COLOR_RESET}\t\t A bug fix"
  echo -e "${COLOR_GREEN}perf${COLOR_RESET}\t\t A code change that improves performance"
  echo -e "${COLOR_GREEN}refactor${COLOR_RESET}\t A code change that neither fixes a bug nor adds a feature"
  echo -e "${COLOR_GREEN}revert${COLOR_RESET}\t\t Reverts a previous commit"
  echo -e "${COLOR_GREEN}style${COLOR_RESET}\t\t Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
  echo -e "${COLOR_GREEN}test${COLOR_RESET}\t\t Adding missing tests or correcting existing tests"
  echo -e "${COLOR_GREEN}types${COLOR_RESET}\t\t Changes that affect the typescript type definitions"
  echo -e "${COLOR_GREEN}wip${COLOR_RESET}\t\t Work in progress (should be removed before merging)"
}
