#!/bin/bash

cloneRepo() {
  # Install Git
  sudo apt update -y && sudo apt install -y git

  # Clone repository
  if [[ ! -d ~/.dotfiles ]]; then
    git clone https://github.com/gtjamesa/.dotfiles.git ~/.dotfiles
  else
    cd ~/.dotfiles
    git fetch origin
    git pull
  fi

  cd "$HOME"
}

bootstrapTerminal() {
  # Ask password
  sudo -v

  # Clone the Git repository
  cloneRepo

  # Install!
  source ~/.dotfiles/installscript "$@"
}

help() {
  cat << EOF
usage: $0 [OPTIONS]
    --help               Show this message
    --all                Install all additional programs and aliases
    --wsl1|--wsl2        Specify that the installation is on WSL v1 or v2
    --[no-]composer      Enable/disable Composer installation (and supporting global packages)
    --[no-]docker        Enable/disable Docker configuration
    --[no-]getracker     Enable/disable GE Tracker specific aliases
EOF
}

for opt in "$@"; do
  case $opt in
    --help)
      help
      exit 0
      ;;
  esac
done

echo 'Bootstrap terminal'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: ' reply

if [[ $reply =~ ^[Yy]$ ]]; then
  bootstrapTerminal
fi
