#!/bin/bash

cloneRepo() {
  # Install Git
  sudo apt update -y && sudo apt install -y git

  # Clone repository
  git clone https://github.com/gtjamesa/.dotfiles.git ~/.dotfiles
}

bootstrapTerminal() {
  # Ask password
	sudo -v

  # Clone the Git repository
  cloneRepo

  # Install!
	source ~/.dotfiles/installscript
}

echo 'Bootstrap terminal'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]
then
   bootstrapTerminal
fi
