#!/bin/bash

OS="$(uname)"

if [[ "$OS" == "Linux" ]]; then
  SHARE_PATH="/usr/share"
elif [[ "$OS" == "Darwin" ]]; then
  SHARE_PATH="/usr/local/share"
fi

backup_file() {
  if [[ -L $1 ]]; then
    echo "Removing symlink $1"
    rm -f "$1"
  elif [[ -f $1 ]]; then
    echo "Creating backup of $1"
    mv "$1" "$1.bak"
  fi
}

symlink_file() {
  backup_file "$2"
  ln -s "$1" "$2"
}

# Install ohmyzsh
# https://github.com/ohmyzsh/ohmyzsh
install_zsh() {
  echo "Installing zsh"
  echo "--------------------"
  if [[ "$OS" == "Linux" ]]; then
    sudo apt install -y zsh
  elif [[ "$OS" == "Darwin" ]]; then
    brew install zsh
  fi

  echo "Installing ohmyzsh"
  echo "--------------------"
  rm -rf "$HOME/.oh-my-zsh/"
  backup_file ~/.zshrc
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  ln -sf "$HOME/.dotfiles/shell/.zshrc" "$HOME/.zshrc"
  ln -s "$HOME/.dotfiles/themes/james-custom.zsh-theme" "$HOME/.oh-my-zsh/themes/"

  echo "Installing ZSH tools"
  echo "--------------------"

  if [[ ! -d "$SHARE_PATH/zsh-autosuggestions" ]]; then
    sudo git clone https://github.com/zsh-users/zsh-autosuggestions.git "$SHARE_PATH/zsh-autosuggestions"
  fi

  if [[ ! -d "$SHARE_PATH/zsh-syntax-highlighting" ]]; then
    sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$SHARE_PATH/zsh-syntax-highlighting"
  fi
}

install_tmux() {
  echo "Installing tmux"
  echo "---------------"

  # Install tmux
  brew install tmux

  # Add tmux plugins
  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"

  # Add tmux config
  symlink_file "$HOME/.dotfiles/shell/.tmux.conf" "$HOME/.tmux.conf"
}

install_fzf() {
  echo "Installing fzf"
  echo "--------------"
  echo
  echo "Recommended answers: Y - Y - N"
  echo "The final N is important - fzf is automatically loaded :)"
  echo
  echo "--------------"
  brew install fzf
  $(brew --prefix)/opt/fzf/install
}

# Install homebrew
# https://docs.brew.sh/Homebrew-on-Linux
install_homebrew() {
  echo "Installing homebrew"
  echo "--------------------"
  rm -rf "$HOME/.linuxbrew"
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  if [[ "$OS" == "Linux" ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  elif [[ "$OS" == "Darwin" ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
}

install_dotfiles() {
  # Add global gitignore
  symlink_file "$HOME/.dotfiles/shell/.global-gitignore" "$HOME/.global-gitignore"
  git config --global core.excludesfile "$HOME/.global-gitignore"

  # Add vimrc
  symlink_file "$HOME/.dotfiles/shell/.vimrc" "$HOME/.vimrc"
}

run_installer() {
  # Install utils
  sudo apt update -y && sudo apt install -y \
    build-essential curl file git wget vim curl php jq

  install_homebrew
  install_zsh
  install_dotfiles
  install_tmux
  install_fzf
}

# TODO: Add aliases from .bashrc/.profile
# TODO: Add WSL specific config
# TODO: Lando alias
# TODO: WSL -> Docker Desktop config (otherwise, install Docker)

run_installer

# Change default shell
chsh -s $(which zsh)

echo "#################################"
echo
echo "- When running tmux for the first time"
echo "-- Press prefix + I (capital i, as in Install) to fetch the plugins"
echo
echo "#################################"
