#!/bin/bash

confirm() {
  while true; do
    read -p "$1 (y/n) " -r
    REPLY=${REPLY:-"y"}
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      return 1
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
      return 0
    fi
  done
}

confirm_zsh() {
  while true; do
    read -k 1 "?$1 (y/n) "
    REPLY=${REPLY:-"y"}
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      return 1
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
      return 0
    fi
  done
}

backup_file() {
  if [ -L "$1" ]; then
    echo "Removing symlink $1"
    rm -f "$1"
  elif [ -f "$1" ]; then
    if [ -n "$2" ]; then
      DST_FILE="$2/$(date +%Y%m%d)-$1"
      echo "Copying $1 to $DST_FILE"
      cp "$1" "$DST_FILE"
    else
      echo "Moving $1 to $1.bak"
      mv "$1" "$1.bak"
    fi
  fi
}

symlink_file() {
  backup_file "$2"
  ln -s "$1" "$2"
}
